language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

jobs:
  include:
    - stage: test
      script: make cc=$cc
      script: make cc=$cc
      script: make cc=$cc
      script: make cc=$cc
      script: make cc=$cc