language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

jobs:
  include:
    - stage: linux
      os: linux
      compiler: g++

    - stage: osx
      os: osx
      compiler: g++

    - os: osx
      compiler: clang++

script: make cc=$cc