name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        g++ Primer++.cpp Primer++.o -o Primer++ --static -std=c++17
    - uses: actions/upload-artifact@v2
      with:
        name: windows_build
        path: Primer++

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        clang++ Primer++.cpp -o Primer++ -std=c++17
    - uses: actions/upload-artifact@v2
      with:
       name: macos_build
       path: Primer++

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        g++ Primer++.cpp -o Primer++ -static -std=c++17
    - uses: actions/upload-artifact@v2
      with:
        name: linux_build
        path: Primer++
