name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        make
    - uses: actions/upload-artifact@v2
      with:
        name: windows_build_raw
        path: Primer++.exe

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        make
    - uses: actions/upload-artifact@v2
      with:
       name: macos_build_dynamic
       path: Primer++

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd ${{ github.workspace }}
        make
    - uses: actions/upload-artifact@v2
      with:
        name: linux_build_static
        path: Primer++
